/*
 * This file is generated by jOOQ.
*/
package de.vorb.npmstat.persistence.jooq.tables.records;


import de.vorb.npmstat.persistence.jooq.tables.DownloadCount;

import java.time.LocalDate;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DownloadCountRecord extends UpdatableRecordImpl<DownloadCountRecord> implements Record3<Long, LocalDate, Integer> {

    private static final long serialVersionUID = 1791792152;

    /**
     * Setter for <code>public.download_count.package_id</code>.
     */
    public DownloadCountRecord setPackageId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.download_count.package_id</code>.
     */
    @NotNull
    public Long getPackageId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.download_count.date</code>.
     */
    public DownloadCountRecord setDate(LocalDate value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.download_count.date</code>.
     */
    @NotNull
    public LocalDate getDate() {
        return (LocalDate) get(1);
    }

    /**
     * Setter for <code>public.download_count.count</code>.
     */
    public DownloadCountRecord setCount(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.download_count.count</code>.
     */
    @NotNull
    public Integer getCount() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Long, LocalDate> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Long, LocalDate, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Long, LocalDate, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return DownloadCount.DOWNLOAD_COUNT.PACKAGE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDate> field2() {
        return DownloadCount.DOWNLOAD_COUNT.DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return DownloadCount.DOWNLOAD_COUNT.COUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getPackageId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDate value2() {
        return getDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DownloadCountRecord value1(Long value) {
        setPackageId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DownloadCountRecord value2(LocalDate value) {
        setDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DownloadCountRecord value3(Integer value) {
        setCount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DownloadCountRecord values(Long value1, LocalDate value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DownloadCountRecord
     */
    public DownloadCountRecord() {
        super(DownloadCount.DOWNLOAD_COUNT);
    }

    /**
     * Create a detached, initialised DownloadCountRecord
     */
    public DownloadCountRecord(Long packageId, LocalDate date, Integer count) {
        super(DownloadCount.DOWNLOAD_COUNT);

        set(0, packageId);
        set(1, date);
        set(2, count);
    }
}
