/*
 * This file is generated by jOOQ.
*/
package de.vorb.npmstat.persistence.jooq.tables.records;


import de.vorb.npmstat.persistence.jooq.tables.IndexesRelationSizePretty;

import jakarta.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IndexesRelationSizePrettyRecord extends TableRecordImpl<IndexesRelationSizePrettyRecord> implements Record2<String, String> {

    private static final long serialVersionUID = -1141459875;

    /**
     * Setter for <code>public.indexes_relation_size_pretty.index_name</code>.
     */
    public IndexesRelationSizePrettyRecord setIndexName(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.indexes_relation_size_pretty.index_name</code>.
     */
    public String getIndexName() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.indexes_relation_size_pretty.total_size</code>.
     */
    public IndexesRelationSizePrettyRecord setTotalSize(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.indexes_relation_size_pretty.total_size</code>.
     */
    public String getTotalSize() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return IndexesRelationSizePretty.INDEXES_RELATION_SIZE_PRETTY.INDEX_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return IndexesRelationSizePretty.INDEXES_RELATION_SIZE_PRETTY.TOTAL_SIZE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getIndexName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getTotalSize();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getIndexName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getTotalSize();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IndexesRelationSizePrettyRecord value1(String value) {
        setIndexName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IndexesRelationSizePrettyRecord value2(String value) {
        setTotalSize(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IndexesRelationSizePrettyRecord values(String value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached IndexesRelationSizePrettyRecord
     */
    public IndexesRelationSizePrettyRecord() {
        super(IndexesRelationSizePretty.INDEXES_RELATION_SIZE_PRETTY);
    }

    /**
     * Create a detached, initialised IndexesRelationSizePrettyRecord
     */
    public IndexesRelationSizePrettyRecord(String indexName, String totalSize) {
        super(IndexesRelationSizePretty.INDEXES_RELATION_SIZE_PRETTY);

        set(0, indexName);
        set(1, totalSize);
    }
}
