/*
 * This file is generated by jOOQ.
*/
package de.vorb.npmstat.persistence.jooq.tables.records;


import de.vorb.npmstat.persistence.jooq.tables.IndexesRelationSize;

import jakarta.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IndexesRelationSizeRecord extends TableRecordImpl<IndexesRelationSizeRecord> implements Record2<String, Long> {

    private static final long serialVersionUID = 544222441;

    /**
     * Setter for <code>public.indexes_relation_size.index_name</code>.
     */
    public IndexesRelationSizeRecord setIndexName(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.indexes_relation_size.index_name</code>.
     */
    public String getIndexName() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.indexes_relation_size.total_bytes</code>.
     */
    public IndexesRelationSizeRecord setTotalBytes(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.indexes_relation_size.total_bytes</code>.
     */
    public Long getTotalBytes() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, Long> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return IndexesRelationSize.INDEXES_RELATION_SIZE.INDEX_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return IndexesRelationSize.INDEXES_RELATION_SIZE.TOTAL_BYTES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getIndexName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getTotalBytes();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getIndexName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getTotalBytes();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IndexesRelationSizeRecord value1(String value) {
        setIndexName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IndexesRelationSizeRecord value2(Long value) {
        setTotalBytes(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IndexesRelationSizeRecord values(String value1, Long value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached IndexesRelationSizeRecord
     */
    public IndexesRelationSizeRecord() {
        super(IndexesRelationSize.INDEXES_RELATION_SIZE);
    }

    /**
     * Create a detached, initialised IndexesRelationSizeRecord
     */
    public IndexesRelationSizeRecord(String indexName, Long totalBytes) {
        super(IndexesRelationSize.INDEXES_RELATION_SIZE);

        set(0, indexName);
        set(1, totalBytes);
    }
}
