/*
 * This file is generated by jOOQ.
*/
package de.vorb.npmstat.persistence.jooq.tables.records;


import de.vorb.npmstat.persistence.jooq.tables.PackageAuthor;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PackageAuthorRecord extends UpdatableRecordImpl<PackageAuthorRecord> implements Record2<Long, Long> {

    private static final long serialVersionUID = -224760767;

    /**
     * Setter for <code>public.package_author.package_id</code>.
     */
    public PackageAuthorRecord setPackageId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.package_author.package_id</code>.
     */
    @NotNull
    public Long getPackageId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.package_author.author_id</code>.
     */
    public PackageAuthorRecord setAuthorId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.package_author.author_id</code>.
     */
    @NotNull
    public Long getAuthorId() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Long, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Long, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Long, Long> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return PackageAuthor.PACKAGE_AUTHOR.PACKAGE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return PackageAuthor.PACKAGE_AUTHOR.AUTHOR_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getPackageId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getAuthorId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PackageAuthorRecord value1(Long value) {
        setPackageId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PackageAuthorRecord value2(Long value) {
        setAuthorId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PackageAuthorRecord values(Long value1, Long value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PackageAuthorRecord
     */
    public PackageAuthorRecord() {
        super(PackageAuthor.PACKAGE_AUTHOR);
    }

    /**
     * Create a detached, initialised PackageAuthorRecord
     */
    public PackageAuthorRecord(Long packageId, Long authorId) {
        super(PackageAuthor.PACKAGE_AUTHOR);

        set(0, packageId);
        set(1, authorId);
    }
}
