/*
 * This file is generated by jOOQ.
 */
package de.vorb.npmstat.persistence.jooq.tables.records;


import de.vorb.npmstat.persistence.jooq.tables.Package;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PackageRecord extends UpdatableRecordImpl<PackageRecord> implements Record3<Long, String, Boolean> {

    private static final long serialVersionUID = 299481285;

    /**
     * Setter for <code>public.package.id</code>.
     */
    public PackageRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.package.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.package.package_name</code>.
     */
    public PackageRecord setPackageName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.package.package_name</code>.
     */
    @NotNull
    @Size(max = 255)
    public String getPackageName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.package.imported</code>.
     */
    public PackageRecord setImported(Boolean value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.package.imported</code>.
     */
    public Boolean getImported() {
        return (Boolean) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Long, String, Boolean> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Long, String, Boolean> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Package.PACKAGE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Package.PACKAGE.PACKAGE_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field3() {
        return Package.PACKAGE.IMPORTED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getPackageName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component3() {
        return getImported();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getPackageName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value3() {
        return getImported();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PackageRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PackageRecord value2(String value) {
        setPackageName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PackageRecord value3(Boolean value) {
        setImported(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PackageRecord values(Long value1, String value2, Boolean value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PackageRecord
     */
    public PackageRecord() {
        super(Package.PACKAGE);
    }

    /**
     * Create a detached, initialised PackageRecord
     */
    public PackageRecord(Long id, String packageName, Boolean imported) {
        super(Package.PACKAGE);

        set(0, id);
        set(1, packageName);
        set(2, imported);
    }
}
