/*
 * This file is generated by jOOQ.
*/
package de.vorb.npmstat.persistence.jooq.tables.records;


import de.vorb.npmstat.persistence.jooq.tables.ShowTablespaces;

import jakarta.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Row1;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ShowTablespacesRecord extends TableRecordImpl<ShowTablespacesRecord> implements Record1<String> {

    private static final long serialVersionUID = 1153233257;

    /**
     * Setter for <code>public.show_tablespaces.show_tablespaces</code>.
     */
    public ShowTablespacesRecord setShowTablespaces(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.show_tablespaces.show_tablespaces</code>.
     */
    public String getShowTablespaces() {
        return (String) get(0);
    }

    // -------------------------------------------------------------------------
    // Record1 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row1<String> fieldsRow() {
        return (Row1) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row1<String> valuesRow() {
        return (Row1) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return ShowTablespaces.SHOW_TABLESPACES.SHOW_TABLESPACES_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getShowTablespaces();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getShowTablespaces();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ShowTablespacesRecord value1(String value) {
        setShowTablespaces(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ShowTablespacesRecord values(String value1) {
        value1(value1);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ShowTablespacesRecord
     */
    public ShowTablespacesRecord() {
        super(ShowTablespaces.SHOW_TABLESPACES);
    }

    /**
     * Create a detached, initialised ShowTablespacesRecord
     */
    public ShowTablespacesRecord(String showTablespaces) {
        super(ShowTablespaces.SHOW_TABLESPACES);

        set(0, showTablespaces);
    }
}
