/*
 * This file is generated by jOOQ.
*/
package de.vorb.npmstat.persistence.jooq.tables;


import de.vorb.npmstat.persistence.jooq.Public;
import de.vorb.npmstat.persistence.jooq.tables.records.ChunkRelationSizePrettyRecord;

import jakarta.annotation.Generated;

import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ChunkRelationSizePretty extends TableImpl<ChunkRelationSizePrettyRecord> {

    private static final long serialVersionUID = 926914681;

    /**
     * The reference instance of <code>public.chunk_relation_size_pretty</code>
     */
    public static final ChunkRelationSizePretty CHUNK_RELATION_SIZE_PRETTY = new ChunkRelationSizePretty();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ChunkRelationSizePrettyRecord> getRecordType() {
        return ChunkRelationSizePrettyRecord.class;
    }

    /**
     * The column <code>public.chunk_relation_size_pretty.chunk_id</code>.
     */
    public final TableField<ChunkRelationSizePrettyRecord, Integer> CHUNK_ID = createField("chunk_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.chunk_relation_size_pretty.chunk_table</code>.
     */
    public final TableField<ChunkRelationSizePrettyRecord, String> CHUNK_TABLE = createField("chunk_table", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.chunk_relation_size_pretty.partitioning_columns</code>.
     */
    public final TableField<ChunkRelationSizePrettyRecord, String[]> PARTITIONING_COLUMNS = createField("partitioning_columns", org.jooq.impl.SQLDataType.VARCHAR.getArrayDataType(), this, "");

    /**
     * The column <code>public.chunk_relation_size_pretty.partitioning_column_types</code>.
     */
    public final TableField<ChunkRelationSizePrettyRecord, Object[]> PARTITIONING_COLUMN_TYPES = createField("partitioning_column_types", org.jooq.impl.DefaultDataType.getDefaultDataType("regtype").getArrayDataType(), this, "");

    /**
     * The column <code>public.chunk_relation_size_pretty.partitioning_hash_functions</code>.
     */
    public final TableField<ChunkRelationSizePrettyRecord, String[]> PARTITIONING_HASH_FUNCTIONS = createField("partitioning_hash_functions", org.jooq.impl.SQLDataType.CLOB.getArrayDataType(), this, "");

    /**
     * The column <code>public.chunk_relation_size_pretty.ranges</code>.
     */
    public final TableField<ChunkRelationSizePrettyRecord, String[]> RANGES = createField("ranges", org.jooq.impl.SQLDataType.CLOB.getArrayDataType(), this, "");

    /**
     * The column <code>public.chunk_relation_size_pretty.table_size</code>.
     */
    public final TableField<ChunkRelationSizePrettyRecord, String> TABLE_SIZE = createField("table_size", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.chunk_relation_size_pretty.index_size</code>.
     */
    public final TableField<ChunkRelationSizePrettyRecord, String> INDEX_SIZE = createField("index_size", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.chunk_relation_size_pretty.toast_size</code>.
     */
    public final TableField<ChunkRelationSizePrettyRecord, String> TOAST_SIZE = createField("toast_size", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.chunk_relation_size_pretty.total_size</code>.
     */
    public final TableField<ChunkRelationSizePrettyRecord, String> TOTAL_SIZE = createField("total_size", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * Create a <code>public.chunk_relation_size_pretty</code> table reference
     */
    public ChunkRelationSizePretty() {
        this(DSL.name("chunk_relation_size_pretty"), null);
    }

    /**
     * Create an aliased <code>public.chunk_relation_size_pretty</code> table reference
     */
    public ChunkRelationSizePretty(String alias) {
        this(DSL.name(alias), CHUNK_RELATION_SIZE_PRETTY);
    }

    /**
     * Create an aliased <code>public.chunk_relation_size_pretty</code> table reference
     */
    public ChunkRelationSizePretty(Name alias) {
        this(alias, CHUNK_RELATION_SIZE_PRETTY);
    }

    private ChunkRelationSizePretty(Name alias, Table<ChunkRelationSizePrettyRecord> aliased) {
        this(alias, aliased, new Field[1]);
    }

    private ChunkRelationSizePretty(Name alias, Table<ChunkRelationSizePrettyRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ChunkRelationSizePretty as(String alias) {
        return new ChunkRelationSizePretty(DSL.name(alias), this, parameters);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ChunkRelationSizePretty as(Name alias) {
        return new ChunkRelationSizePretty(alias, this, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public ChunkRelationSizePretty rename(String name) {
        return new ChunkRelationSizePretty(DSL.name(name), null, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public ChunkRelationSizePretty rename(Name name) {
        return new ChunkRelationSizePretty(name, null, parameters);
    }

    /**
     * Call this table-valued function
     */
    public ChunkRelationSizePretty call(Object mainTable) {
        return new ChunkRelationSizePretty(DSL.name(getName()), null, new Field[] { 
              DSL.val(mainTable, org.jooq.impl.DefaultDataType.getDefaultDataType("regclass"))
        });
    }

    /**
     * Call this table-valued function
     */
    public ChunkRelationSizePretty call(Field<Object> mainTable) {
        return new ChunkRelationSizePretty(DSL.name(getName()), null, new Field[] { 
              mainTable
        });
    }
}
