/*
 * This file is generated by jOOQ.
*/
package de.vorb.npmstat.persistence.jooq.tables;


import de.vorb.npmstat.persistence.jooq.Public;
import de.vorb.npmstat.persistence.jooq.tables.records.HypertableRelationSizePrettyRecord;

import jakarta.annotation.Generated;

import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class HypertableRelationSizePretty extends TableImpl<HypertableRelationSizePrettyRecord> {

    private static final long serialVersionUID = -546150723;

    /**
     * The reference instance of <code>public.hypertable_relation_size_pretty</code>
     */
    public static final HypertableRelationSizePretty HYPERTABLE_RELATION_SIZE_PRETTY = new HypertableRelationSizePretty();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<HypertableRelationSizePrettyRecord> getRecordType() {
        return HypertableRelationSizePrettyRecord.class;
    }

    /**
     * The column <code>public.hypertable_relation_size_pretty.table_size</code>.
     */
    public final TableField<HypertableRelationSizePrettyRecord, String> TABLE_SIZE = createField("table_size", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.hypertable_relation_size_pretty.index_size</code>.
     */
    public final TableField<HypertableRelationSizePrettyRecord, String> INDEX_SIZE = createField("index_size", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.hypertable_relation_size_pretty.toast_size</code>.
     */
    public final TableField<HypertableRelationSizePrettyRecord, String> TOAST_SIZE = createField("toast_size", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.hypertable_relation_size_pretty.total_size</code>.
     */
    public final TableField<HypertableRelationSizePrettyRecord, String> TOTAL_SIZE = createField("total_size", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * Create a <code>public.hypertable_relation_size_pretty</code> table reference
     */
    public HypertableRelationSizePretty() {
        this(DSL.name("hypertable_relation_size_pretty"), null);
    }

    /**
     * Create an aliased <code>public.hypertable_relation_size_pretty</code> table reference
     */
    public HypertableRelationSizePretty(String alias) {
        this(DSL.name(alias), HYPERTABLE_RELATION_SIZE_PRETTY);
    }

    /**
     * Create an aliased <code>public.hypertable_relation_size_pretty</code> table reference
     */
    public HypertableRelationSizePretty(Name alias) {
        this(alias, HYPERTABLE_RELATION_SIZE_PRETTY);
    }

    private HypertableRelationSizePretty(Name alias, Table<HypertableRelationSizePrettyRecord> aliased) {
        this(alias, aliased, new Field[1]);
    }

    private HypertableRelationSizePretty(Name alias, Table<HypertableRelationSizePrettyRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HypertableRelationSizePretty as(String alias) {
        return new HypertableRelationSizePretty(DSL.name(alias), this, parameters);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HypertableRelationSizePretty as(Name alias) {
        return new HypertableRelationSizePretty(alias, this, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public HypertableRelationSizePretty rename(String name) {
        return new HypertableRelationSizePretty(DSL.name(name), null, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public HypertableRelationSizePretty rename(Name name) {
        return new HypertableRelationSizePretty(name, null, parameters);
    }

    /**
     * Call this table-valued function
     */
    public HypertableRelationSizePretty call(Object mainTable) {
        return new HypertableRelationSizePretty(DSL.name(getName()), null, new Field[] { 
              DSL.val(mainTable, org.jooq.impl.DefaultDataType.getDefaultDataType("regclass"))
        });
    }

    /**
     * Call this table-valued function
     */
    public HypertableRelationSizePretty call(Field<Object> mainTable) {
        return new HypertableRelationSizePretty(DSL.name(getName()), null, new Field[] { 
              mainTable
        });
    }
}
