/*
 * Copyright 2012-2017 the original author or authors.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/*
 * This file is generated by jOOQ.
*/
package de.vorb.npmstat.persistence.jooq.tables;


import de.vorb.npmstat.persistence.jooq.Keys;
import de.vorb.npmstat.persistence.jooq.Public;
import de.vorb.npmstat.persistence.jooq.tables.records.PackageRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Package extends TableImpl<PackageRecord> {

    private static final long serialVersionUID = -1917644941;

    /**
     * The reference instance of <code>public.package</code>
     */
    public static final Package PACKAGE = new Package();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PackageRecord> getRecordType() {
        return PackageRecord.class;
    }

    /**
     * The column <code>public.package.id</code>.
     */
    public final TableField<PackageRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('package_id_seq'::regclass)", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>public.package.name</code>.
     */
    public final TableField<PackageRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

    /**
     * Create a <code>public.package</code> table reference
     */
    public Package() {
        this("package", null);
    }

    /**
     * Create an aliased <code>public.package</code> table reference
     */
    public Package(String alias) {
        this(alias, PACKAGE);
    }

    private Package(String alias, Table<PackageRecord> aliased) {
        this(alias, aliased, null);
    }

    private Package(String alias, Table<PackageRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<PackageRecord, Long> getIdentity() {
        return Keys.IDENTITY_PACKAGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<PackageRecord> getPrimaryKey() {
        return Keys.PACKAGE_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<PackageRecord>> getKeys() {
        return Arrays.<UniqueKey<PackageRecord>>asList(Keys.PACKAGE_PKEY, Keys.PACKAGE_NAME_KEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Package as(String alias) {
        return new Package(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Package rename(String name) {
        return new Package(name, null);
    }
}
