/*
 * This file is generated by jOOQ.
 */
package de.vorb.npmstat.persistence.jooq.tables;


import de.vorb.npmstat.persistence.jooq.Indexes;
import de.vorb.npmstat.persistence.jooq.Keys;
import de.vorb.npmstat.persistence.jooq.Public;
import de.vorb.npmstat.persistence.jooq.tables.records.PackageRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Package extends TableImpl<PackageRecord> {

    private static final long serialVersionUID = -753293601;

    /**
     * The reference instance of <code>public.package</code>
     */
    public static final Package PACKAGE = new Package();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PackageRecord> getRecordType() {
        return PackageRecord.class;
    }

    /**
     * The column <code>public.package.id</code>.
     */
    public final TableField<PackageRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('package_id_seq'::regclass)", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>public.package.name</code>.
     */
    public final TableField<PackageRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.package.imported</code>.
     */
    public final TableField<PackageRecord, Boolean> IMPORTED = createField("imported", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false).defaultValue(org.jooq.impl.DSL.field("false", org.jooq.impl.SQLDataType.BOOLEAN)), this, "");

    /**
     * Create a <code>public.package</code> table reference
     */
    public Package() {
        this(DSL.name("package"), null);
    }

    /**
     * Create an aliased <code>public.package</code> table reference
     */
    public Package(String alias) {
        this(DSL.name(alias), PACKAGE);
    }

    /**
     * Create an aliased <code>public.package</code> table reference
     */
    public Package(Name alias) {
        this(alias, PACKAGE);
    }

    private Package(Name alias, Table<PackageRecord> aliased) {
        this(alias, aliased, null);
    }

    private Package(Name alias, Table<PackageRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Package(Table<O> child, ForeignKey<O, PackageRecord> key) {
        super(child, key, PACKAGE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PACKAGE_NAME_KEY, Indexes.PACKAGE_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<PackageRecord, Long> getIdentity() {
        return Keys.IDENTITY_PACKAGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<PackageRecord> getPrimaryKey() {
        return Keys.PACKAGE_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<PackageRecord>> getKeys() {
        return Arrays.<UniqueKey<PackageRecord>>asList(Keys.PACKAGE_PKEY, Keys.PACKAGE_NAME_KEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Package as(String alias) {
        return new Package(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Package as(Name alias) {
        return new Package(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Package rename(String name) {
        return new Package(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Package rename(Name name) {
        return new Package(name, null);
    }
}
