/*
 * This file is generated by jOOQ.
*/
package de.vorb.npmstat.persistence.jooq.tables;


import de.vorb.npmstat.persistence.jooq.Public;
import de.vorb.npmstat.persistence.jooq.tables.records.ShowTablespacesRecord;

import jakarta.annotation.Generated;

import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ShowTablespaces extends TableImpl<ShowTablespacesRecord> {

    private static final long serialVersionUID = -1311364576;

    /**
     * The reference instance of <code>public.show_tablespaces</code>
     */
    public static final ShowTablespaces SHOW_TABLESPACES = new ShowTablespaces();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ShowTablespacesRecord> getRecordType() {
        return ShowTablespacesRecord.class;
    }

    /**
     * The column <code>public.show_tablespaces.show_tablespaces</code>.
     */
    public final TableField<ShowTablespacesRecord, String> SHOW_TABLESPACES_ = createField("show_tablespaces", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * Create a <code>public.show_tablespaces</code> table reference
     */
    public ShowTablespaces() {
        this(DSL.name("show_tablespaces"), null);
    }

    /**
     * Create an aliased <code>public.show_tablespaces</code> table reference
     */
    public ShowTablespaces(String alias) {
        this(DSL.name(alias), SHOW_TABLESPACES);
    }

    /**
     * Create an aliased <code>public.show_tablespaces</code> table reference
     */
    public ShowTablespaces(Name alias) {
        this(alias, SHOW_TABLESPACES);
    }

    private ShowTablespaces(Name alias, Table<ShowTablespacesRecord> aliased) {
        this(alias, aliased, new Field[1]);
    }

    private ShowTablespaces(Name alias, Table<ShowTablespacesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ShowTablespaces as(String alias) {
        return new ShowTablespaces(DSL.name(alias), this, parameters);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ShowTablespaces as(Name alias) {
        return new ShowTablespaces(alias, this, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public ShowTablespaces rename(String name) {
        return new ShowTablespaces(DSL.name(name), null, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public ShowTablespaces rename(Name name) {
        return new ShowTablespaces(name, null, parameters);
    }

    /**
     * Call this table-valued function
     */
    public ShowTablespaces call(Object hypertable) {
        return new ShowTablespaces(DSL.name(getName()), null, new Field[] { 
              DSL.val(hypertable, org.jooq.impl.DefaultDataType.getDefaultDataType("regclass"))
        });
    }

    /**
     * Call this table-valued function
     */
    public ShowTablespaces call(Field<Object> hypertable) {
        return new ShowTablespaces(DSL.name(getName()), null, new Field[] { 
              hypertable
        });
    }
}
