/*
 * Copyright 2012-2017 the original author or authors.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/*
 * This file is generated by jOOQ.
*/
package de.vorb.npmstat.persistence.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDate;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DownloadCount implements Serializable {

    private static final long serialVersionUID = -959286125;

    private Long      packageId;
    private LocalDate date;
    private Integer   count;

    public DownloadCount() {}

    public DownloadCount(DownloadCount value) {
        this.packageId = value.packageId;
        this.date = value.date;
        this.count = value.count;
    }

    public DownloadCount(
        Long      packageId,
        LocalDate date,
        Integer   count
    ) {
        this.packageId = packageId;
        this.date = date;
        this.count = count;
    }

    @NotNull
    public Long getPackageId() {
        return this.packageId;
    }

    public DownloadCount setPackageId(Long packageId) {
        this.packageId = packageId;
        return this;
    }

    @NotNull
    public LocalDate getDate() {
        return this.date;
    }

    public DownloadCount setDate(LocalDate date) {
        this.date = date;
        return this;
    }

    @NotNull
    public Integer getCount() {
        return this.count;
    }

    public DownloadCount setCount(Integer count) {
        this.count = count;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final DownloadCount other = (DownloadCount) obj;
        if (packageId == null) {
            if (other.packageId != null)
                return false;
        }
        else if (!packageId.equals(other.packageId))
            return false;
        if (date == null) {
            if (other.date != null)
                return false;
        }
        else if (!date.equals(other.date))
            return false;
        if (count == null) {
            if (other.count != null)
                return false;
        }
        else if (!count.equals(other.count))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.packageId == null) ? 0 : this.packageId.hashCode());
        result = prime * result + ((this.date == null) ? 0 : this.date.hashCode());
        result = prime * result + ((this.count == null) ? 0 : this.count.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("DownloadCount (");

        sb.append(packageId);
        sb.append(", ").append(date);
        sb.append(", ").append(count);

        sb.append(")");
        return sb.toString();
    }
}
