/*
 * This file is generated by jOOQ.
*/
package de.vorb.npmstat.persistence.jooq.tables.pojos;


import java.io.Serializable;

import jakarta.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IndexesRelationSizePretty implements Serializable {

    private static final long serialVersionUID = -1474534859;

    private String indexName;
    private String totalSize;

    public IndexesRelationSizePretty() {}

    public IndexesRelationSizePretty(IndexesRelationSizePretty value) {
        this.indexName = value.indexName;
        this.totalSize = value.totalSize;
    }

    public IndexesRelationSizePretty(
        String indexName,
        String totalSize
    ) {
        this.indexName = indexName;
        this.totalSize = totalSize;
    }

    public String getIndexName() {
        return this.indexName;
    }

    public IndexesRelationSizePretty setIndexName(String indexName) {
        this.indexName = indexName;
        return this;
    }

    public String getTotalSize() {
        return this.totalSize;
    }

    public IndexesRelationSizePretty setTotalSize(String totalSize) {
        this.totalSize = totalSize;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final IndexesRelationSizePretty other = (IndexesRelationSizePretty) obj;
        if (indexName == null) {
            if (other.indexName != null)
                return false;
        }
        else if (!indexName.equals(other.indexName))
            return false;
        if (totalSize == null) {
            if (other.totalSize != null)
                return false;
        }
        else if (!totalSize.equals(other.totalSize))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.indexName == null) ? 0 : this.indexName.hashCode());
        result = prime * result + ((this.totalSize == null) ? 0 : this.totalSize.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("IndexesRelationSizePretty (");

        sb.append(indexName);
        sb.append(", ").append(totalSize);

        sb.append(")");
        return sb.toString();
    }
}
