/*
 * This file is generated by jOOQ.
*/
package de.vorb.npmstat.persistence.jooq.tables.pojos;


import java.io.Serializable;

import jakarta.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IndexesRelationSize implements Serializable {

    private static final long serialVersionUID = 1609736855;

    private String indexName;
    private Long   totalBytes;

    public IndexesRelationSize() {}

    public IndexesRelationSize(IndexesRelationSize value) {
        this.indexName = value.indexName;
        this.totalBytes = value.totalBytes;
    }

    public IndexesRelationSize(
        String indexName,
        Long   totalBytes
    ) {
        this.indexName = indexName;
        this.totalBytes = totalBytes;
    }

    public String getIndexName() {
        return this.indexName;
    }

    public IndexesRelationSize setIndexName(String indexName) {
        this.indexName = indexName;
        return this;
    }

    public Long getTotalBytes() {
        return this.totalBytes;
    }

    public IndexesRelationSize setTotalBytes(Long totalBytes) {
        this.totalBytes = totalBytes;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final IndexesRelationSize other = (IndexesRelationSize) obj;
        if (indexName == null) {
            if (other.indexName != null)
                return false;
        }
        else if (!indexName.equals(other.indexName))
            return false;
        if (totalBytes == null) {
            if (other.totalBytes != null)
                return false;
        }
        else if (!totalBytes.equals(other.totalBytes))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.indexName == null) ? 0 : this.indexName.hashCode());
        result = prime * result + ((this.totalBytes == null) ? 0 : this.totalBytes.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("IndexesRelationSize (");

        sb.append(indexName);
        sb.append(", ").append(totalBytes);

        sb.append(")");
        return sb.toString();
    }
}
