/*
 * This file is generated by jOOQ.
 */
package de.vorb.npmstat.persistence.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Package implements Serializable {

    private static final long serialVersionUID = -1574704937;

    private Long    id;
    private String  name;
    private Boolean imported;

    public Package() {}

    public Package(Package value) {
        this.id = value.id;
        this.name = value.name;
        this.imported = value.imported;
    }

    public Package(
        Long    id,
        String  name,
        Boolean imported
    ) {
        this.id = id;
        this.name = name;
        this.imported = imported;
    }

    public Long getId() {
        return this.id;
    }

    public Package setId(Long id) {
        this.id = id;
        return this;
    }

    @NotNull
    @Size(max = 255)
    public String getName() {
        return this.name;
    }

    public Package setName(String name) {
        this.name = name;
        return this;
    }

    public Boolean getImported() {
        return this.imported;
    }

    public Package setImported(Boolean imported) {
        this.imported = imported;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Package other = (Package) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (name == null) {
            if (other.name != null)
                return false;
        }
        else if (!name.equals(other.name))
            return false;
        if (imported == null) {
            if (other.imported != null)
                return false;
        }
        else if (!imported.equals(other.imported))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.imported == null) ? 0 : this.imported.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Package (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(imported);

        sb.append(")");
        return sb.toString();
    }
}
