/*
 * Copyright 2012-2017 the original author or authors.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/*
 * This file is generated by jOOQ.
*/
package de.vorb.npmstat.persistence.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PackageAuthor implements Serializable {

    private static final long serialVersionUID = -2086086690;

    private Long packageId;
    private Long authorId;

    public PackageAuthor() {}

    public PackageAuthor(PackageAuthor value) {
        this.packageId = value.packageId;
        this.authorId = value.authorId;
    }

    public PackageAuthor(
        Long packageId,
        Long authorId
    ) {
        this.packageId = packageId;
        this.authorId = authorId;
    }

    @NotNull
    public Long getPackageId() {
        return this.packageId;
    }

    public PackageAuthor setPackageId(Long packageId) {
        this.packageId = packageId;
        return this;
    }

    @NotNull
    public Long getAuthorId() {
        return this.authorId;
    }

    public PackageAuthor setAuthorId(Long authorId) {
        this.authorId = authorId;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final PackageAuthor other = (PackageAuthor) obj;
        if (packageId == null) {
            if (other.packageId != null)
                return false;
        }
        else if (!packageId.equals(other.packageId))
            return false;
        if (authorId == null) {
            if (other.authorId != null)
                return false;
        }
        else if (!authorId.equals(other.authorId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.packageId == null) ? 0 : this.packageId.hashCode());
        result = prime * result + ((this.authorId == null) ? 0 : this.authorId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PackageAuthor (");

        sb.append(packageId);
        sb.append(", ").append(authorId);

        sb.append(")");
        return sb.toString();
    }
}
