/*
 * This file is generated by jOOQ.
*/
package de.vorb.npmstat.persistence.jooq.tables.pojos;


import java.io.Serializable;

import jakarta.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ShowTablespaces implements Serializable {

    private static final long serialVersionUID = 696116628;

    private String showTablespaces;

    public ShowTablespaces() {}

    public ShowTablespaces(ShowTablespaces value) {
        this.showTablespaces = value.showTablespaces;
    }

    public ShowTablespaces(
        String showTablespaces
    ) {
        this.showTablespaces = showTablespaces;
    }

    public String getShowTablespaces() {
        return this.showTablespaces;
    }

    public ShowTablespaces setShowTablespaces(String showTablespaces) {
        this.showTablespaces = showTablespaces;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final ShowTablespaces other = (ShowTablespaces) obj;
        if (showTablespaces == null) {
            if (other.showTablespaces != null)
                return false;
        }
        else if (!showTablespaces.equals(other.showTablespaces))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.showTablespaces == null) ? 0 : this.showTablespaces.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ShowTablespaces (");

        sb.append(showTablespaces);

        sb.append(")");
        return sb.toString();
    }
}
