/*
 * This file is generated by jOOQ.
*/
package de.vorb.npmstat.persistence.jooq.routines;


import de.vorb.npmstat.persistence.jooq.Public;

import jakarta.annotation.Generated;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AddDimension extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = 1315778722;

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration.
     */
    @java.lang.Deprecated
    public static final Parameter<Object> MAIN_TABLE = createParameter("main_table", org.jooq.impl.DefaultDataType.getDefaultDataType("regclass"), false, false);

    /**
     * The parameter <code>public.add_dimension.column_name</code>.
     */
    public static final Parameter<String> COLUMN_NAME = createParameter("column_name", org.jooq.impl.SQLDataType.VARCHAR, false, false);

    /**
     * The parameter <code>public.add_dimension.number_partitions</code>.
     */
    public static final Parameter<Integer> NUMBER_PARTITIONS = createParameter("number_partitions", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("NULL::integer", org.jooq.impl.SQLDataType.INTEGER)), true, false);

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration.
     */
    @java.lang.Deprecated
    public static final Parameter<Object> CHUNK_TIME_INTERVAL = createParameter("chunk_time_interval", org.jooq.impl.DefaultDataType.getDefaultDataType("anyelement"), true, false);

    /**
     * The parameter <code>public.add_dimension.partitioning_func</code>.
     */
    public static final Parameter<String> PARTITIONING_FUNC = createParameter("partitioning_func", org.jooq.impl.SQLDataType.VARCHAR.defaultValue(org.jooq.impl.DSL.field("NULL::regproc", org.jooq.impl.SQLDataType.VARCHAR)), true, false);

    /**
     * The parameter <code>public.add_dimension.if_not_exists</code>.
     */
    public static final Parameter<Boolean> IF_NOT_EXISTS = createParameter("if_not_exists", org.jooq.impl.SQLDataType.BOOLEAN.defaultValue(org.jooq.impl.DSL.field("false", org.jooq.impl.SQLDataType.BOOLEAN)), true, false);

    /**
     * Create a new routine call instance
     */
    public AddDimension() {
        super("add_dimension", Public.PUBLIC);

        addInParameter(MAIN_TABLE);
        addInParameter(COLUMN_NAME);
        addInParameter(NUMBER_PARTITIONS);
        addInParameter(CHUNK_TIME_INTERVAL);
        addInParameter(PARTITIONING_FUNC);
        addInParameter(IF_NOT_EXISTS);
    }

    /**
     * Set the <code>main_table</code> parameter IN value to the routine
     */
    public void setMainTable(Object value) {
        setValue(MAIN_TABLE, value);
    }

    /**
     * Set the <code>column_name</code> parameter IN value to the routine
     */
    public void setColumnName(String value) {
        setValue(COLUMN_NAME, value);
    }

    /**
     * Set the <code>number_partitions</code> parameter IN value to the routine
     */
    public void setNumberPartitions(Integer value) {
        setValue(NUMBER_PARTITIONS, value);
    }

    /**
     * Set the <code>chunk_time_interval</code> parameter IN value to the routine
     */
    public void setChunkTimeInterval(Object value) {
        setValue(CHUNK_TIME_INTERVAL, value);
    }

    /**
     * Set the <code>partitioning_func</code> parameter IN value to the routine
     */
    public void setPartitioningFunc(String value) {
        setValue(PARTITIONING_FUNC, value);
    }

    /**
     * Set the <code>if_not_exists</code> parameter IN value to the routine
     */
    public void setIfNotExists(Boolean value) {
        setValue(IF_NOT_EXISTS, value);
    }
}
