/*
 * This file is generated by jOOQ.
*/
package de.vorb.npmstat.persistence.jooq.routines;


import de.vorb.npmstat.persistence.jooq.Public;

import jakarta.annotation.Generated;

import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DetachTablespace extends AbstractRoutine<Integer> {

    private static final long serialVersionUID = 1224083967;

    /**
     * The parameter <code>public.detach_tablespace.RETURN_VALUE</code>.
     */
    public static final Parameter<Integer> RETURN_VALUE = createParameter("RETURN_VALUE", org.jooq.impl.SQLDataType.INTEGER, false, false);

    /**
     * The parameter <code>public.detach_tablespace.tablespace</code>.
     */
    public static final Parameter<String> TABLESPACE = createParameter("tablespace", org.jooq.impl.SQLDataType.VARCHAR, false, false);

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration.
     */
    @java.lang.Deprecated
    public static final Parameter<Object> HYPERTABLE = createParameter("hypertable", org.jooq.impl.DefaultDataType.getDefaultDataType("regclass"), true, false);

    /**
     * The parameter <code>public.detach_tablespace.if_attached</code>.
     */
    public static final Parameter<Boolean> IF_ATTACHED = createParameter("if_attached", org.jooq.impl.SQLDataType.BOOLEAN.defaultValue(org.jooq.impl.DSL.field("false", org.jooq.impl.SQLDataType.BOOLEAN)), true, false);

    /**
     * Create a new routine call instance
     */
    public DetachTablespace() {
        super("detach_tablespace", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER);

        setReturnParameter(RETURN_VALUE);
        addInParameter(TABLESPACE);
        addInParameter(HYPERTABLE);
        addInParameter(IF_ATTACHED);
    }

    /**
     * Set the <code>tablespace</code> parameter IN value to the routine
     */
    public void setTablespace(String value) {
        setValue(TABLESPACE, value);
    }

    /**
     * Set the <code>tablespace</code> parameter to the function to be used with a {@link org.jooq.Select} statement
     */
    public DetachTablespace setTablespace(Field<String> field) {
        setField(TABLESPACE, field);
        return this;
    }

    /**
     * Set the <code>hypertable</code> parameter IN value to the routine
     */
    public void setHypertable(Object value) {
        setValue(HYPERTABLE, value);
    }

    /**
     * Set the <code>hypertable</code> parameter to the function to be used with a {@link org.jooq.Select} statement
     */
    public DetachTablespace setHypertable(Field<Object> field) {
        setField(HYPERTABLE, field);
        return this;
    }

    /**
     * Set the <code>if_attached</code> parameter IN value to the routine
     */
    public void setIfAttached(Boolean value) {
        setValue(IF_ATTACHED, value);
    }

    /**
     * Set the <code>if_attached</code> parameter to the function to be used with a {@link org.jooq.Select} statement
     */
    public DetachTablespace setIfAttached(Field<Boolean> field) {
        setField(IF_ATTACHED, field);
        return this;
    }
}
