/*
 * This file is generated by jOOQ.
*/
package de.vorb.npmstat.persistence.jooq.routines;


import de.vorb.npmstat.persistence.jooq.Public;

import jakarta.annotation.Generated;

import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TimeBucket12 extends AbstractRoutine<Short> {

    private static final long serialVersionUID = 1642344302;

    /**
     * The parameter <code>public.time_bucket.RETURN_VALUE</code>.
     */
    public static final Parameter<Short> RETURN_VALUE = createParameter("RETURN_VALUE", org.jooq.impl.SQLDataType.SMALLINT, false, false);

    /**
     * The parameter <code>public.time_bucket.bucket_width</code>.
     */
    public static final Parameter<Short> BUCKET_WIDTH = createParameter("bucket_width", org.jooq.impl.SQLDataType.SMALLINT, false, false);

    /**
     * The parameter <code>public.time_bucket.ts</code>.
     */
    public static final Parameter<Short> TS = createParameter("ts", org.jooq.impl.SQLDataType.SMALLINT, false, false);

    /**
     * The parameter <code>public.time_bucket.offset</code>.
     */
    public static final Parameter<Short> OFFSET = createParameter("offset", org.jooq.impl.SQLDataType.SMALLINT, false, false);

    /**
     * Create a new routine call instance
     */
    public TimeBucket12() {
        super("time_bucket", Public.PUBLIC, org.jooq.impl.SQLDataType.SMALLINT);

        setReturnParameter(RETURN_VALUE);
        addInParameter(BUCKET_WIDTH);
        addInParameter(TS);
        addInParameter(OFFSET);
        setOverloaded(true);
    }

    /**
     * Set the <code>bucket_width</code> parameter IN value to the routine
     */
    public void setBucketWidth(Short value) {
        setValue(BUCKET_WIDTH, value);
    }

    /**
     * Set the <code>bucket_width</code> parameter to the function to be used with a {@link org.jooq.Select} statement
     */
    public TimeBucket12 setBucketWidth(Field<Short> field) {
        setField(BUCKET_WIDTH, field);
        return this;
    }

    /**
     * Set the <code>ts</code> parameter IN value to the routine
     */
    public void setTs(Short value) {
        setValue(TS, value);
    }

    /**
     * Set the <code>ts</code> parameter to the function to be used with a {@link org.jooq.Select} statement
     */
    public TimeBucket12 setTs(Field<Short> field) {
        setField(TS, field);
        return this;
    }

    /**
     * Set the <code>offset</code> parameter IN value to the routine
     */
    public void setOffset(Short value) {
        setValue(OFFSET, value);
    }

    /**
     * Set the <code>offset</code> parameter to the function to be used with a {@link org.jooq.Select} statement
     */
    public TimeBucket12 setOffset(Field<Short> field) {
        setField(OFFSET, field);
        return this;
    }
}
