/*
 * This file is generated by jOOQ.
*/
package de.vorb.npmstat.persistence.jooq.routines;


import de.vorb.npmstat.persistence.jooq.Public;

import java.time.OffsetDateTime;

import jakarta.annotation.Generated;

import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TimeBucket5 extends AbstractRoutine<OffsetDateTime> {

    private static final long serialVersionUID = -944858456;

    /**
     * The parameter <code>public.time_bucket.RETURN_VALUE</code>.
     */
    public static final Parameter<OffsetDateTime> RETURN_VALUE = createParameter("RETURN_VALUE", org.jooq.impl.SQLDataType.TIMESTAMPWITHTIMEZONE, false, false);

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration.
     */
    @java.lang.Deprecated
    public static final Parameter<Object> BUCKET_WIDTH = createParameter("bucket_width", org.jooq.impl.DefaultDataType.getDefaultDataType("interval"), false, false);

    /**
     * The parameter <code>public.time_bucket.ts</code>.
     */
    public static final Parameter<OffsetDateTime> TS = createParameter("ts", org.jooq.impl.SQLDataType.TIMESTAMPWITHTIMEZONE, false, false);

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration.
     */
    @java.lang.Deprecated
    public static final Parameter<Object> OFFSET = createParameter("offset", org.jooq.impl.DefaultDataType.getDefaultDataType("interval"), false, false);

    /**
     * Create a new routine call instance
     */
    public TimeBucket5() {
        super("time_bucket", Public.PUBLIC, org.jooq.impl.SQLDataType.TIMESTAMPWITHTIMEZONE);

        setReturnParameter(RETURN_VALUE);
        addInParameter(BUCKET_WIDTH);
        addInParameter(TS);
        addInParameter(OFFSET);
        setOverloaded(true);
    }

    /**
     * Set the <code>bucket_width</code> parameter IN value to the routine
     */
    public void setBucketWidth(Object value) {
        setValue(BUCKET_WIDTH, value);
    }

    /**
     * Set the <code>bucket_width</code> parameter to the function to be used with a {@link org.jooq.Select} statement
     */
    public TimeBucket5 setBucketWidth(Field<Object> field) {
        setField(BUCKET_WIDTH, field);
        return this;
    }

    /**
     * Set the <code>ts</code> parameter IN value to the routine
     */
    public void setTs(OffsetDateTime value) {
        setValue(TS, value);
    }

    /**
     * Set the <code>ts</code> parameter to the function to be used with a {@link org.jooq.Select} statement
     */
    public TimeBucket5 setTs(Field<OffsetDateTime> field) {
        setField(TS, field);
        return this;
    }

    /**
     * Set the <code>offset</code> parameter IN value to the routine
     */
    public void setOffset(Object value) {
        setValue(OFFSET, value);
    }

    /**
     * Set the <code>offset</code> parameter to the function to be used with a {@link org.jooq.Select} statement
     */
    public TimeBucket5 setOffset(Field<Object> field) {
        setField(OFFSET, field);
        return this;
    }
}
