/*
 * This file is generated by jOOQ.
 */
package de.vorb.npmstat.persistence.jooq;


import de.vorb.npmstat.persistence.jooq.tables.DownloadCount;
import de.vorb.npmstat.persistence.jooq.tables.Package;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index DOWNLOAD_COUNT_DATE_IDX = Indexes0.DOWNLOAD_COUNT_DATE_IDX;
    public static final Index DOWNLOAD_COUNT_PKEY = Indexes0.DOWNLOAD_COUNT_PKEY;
    public static final Index PACKAGE_PACKAGE_NAME_KEY = Indexes0.PACKAGE_PACKAGE_NAME_KEY;
    public static final Index PACKAGE_PKEY = Indexes0.PACKAGE_PKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index DOWNLOAD_COUNT_DATE_IDX = Internal.createIndex("download_count_date_idx", DownloadCount.DOWNLOAD_COUNT, new OrderField[] { DownloadCount.DOWNLOAD_COUNT.DATE.desc() }, false);
        public static Index DOWNLOAD_COUNT_PKEY = Internal.createIndex("download_count_pkey", DownloadCount.DOWNLOAD_COUNT, new OrderField[] { DownloadCount.DOWNLOAD_COUNT.PACKAGE_NAME, DownloadCount.DOWNLOAD_COUNT.DATE }, true);
        public static Index PACKAGE_PACKAGE_NAME_KEY = Internal.createIndex("package_package_name_key", Package.PACKAGE, new OrderField[] { Package.PACKAGE.PACKAGE_NAME }, true);
        public static Index PACKAGE_PKEY = Internal.createIndex("package_pkey", Package.PACKAGE, new OrderField[] { Package.PACKAGE.ID }, true);
    }
}
