/*
 * This file is generated by jOOQ.
 */
package de.vorb.npmstat.persistence.jooq;


import de.vorb.npmstat.persistence.jooq.tables.DownloadCount;
import de.vorb.npmstat.persistence.jooq.tables.Package;
import de.vorb.npmstat.persistence.jooq.tables.records.DownloadCountRecord;
import de.vorb.npmstat.persistence.jooq.tables.records.PackageRecord;

import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<PackageRecord, Long> IDENTITY_PACKAGE = Identities0.IDENTITY_PACKAGE;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<DownloadCountRecord> DOWNLOAD_COUNT_PKEY = UniqueKeys0.DOWNLOAD_COUNT_PKEY;
    public static final UniqueKey<PackageRecord> PACKAGE_PKEY = UniqueKeys0.PACKAGE_PKEY;
    public static final UniqueKey<PackageRecord> PACKAGE_PACKAGE_NAME_KEY = UniqueKeys0.PACKAGE_PACKAGE_NAME_KEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<PackageRecord, Long> IDENTITY_PACKAGE = Internal.createIdentity(Package.PACKAGE, Package.PACKAGE.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<DownloadCountRecord> DOWNLOAD_COUNT_PKEY = Internal.createUniqueKey(DownloadCount.DOWNLOAD_COUNT, "download_count_pkey", DownloadCount.DOWNLOAD_COUNT.PACKAGE_NAME, DownloadCount.DOWNLOAD_COUNT.DATE);
        public static final UniqueKey<PackageRecord> PACKAGE_PKEY = Internal.createUniqueKey(Package.PACKAGE, "package_pkey", Package.PACKAGE.ID);
        public static final UniqueKey<PackageRecord> PACKAGE_PACKAGE_NAME_KEY = Internal.createUniqueKey(Package.PACKAGE, "package_package_name_key", Package.PACKAGE.PACKAGE_NAME);
    }
}
