/*
 * This file is generated by jOOQ.
*/
package de.vorb.npmstat.persistence.jooq;


import de.vorb.npmstat.persistence.jooq.tables.Author;
import de.vorb.npmstat.persistence.jooq.tables.DownloadCount;
import de.vorb.npmstat.persistence.jooq.tables.Package;
import de.vorb.npmstat.persistence.jooq.tables.PackageAuthor;
import de.vorb.npmstat.persistence.jooq.tables.records.AuthorRecord;
import de.vorb.npmstat.persistence.jooq.tables.records.DownloadCountRecord;
import de.vorb.npmstat.persistence.jooq.tables.records.PackageAuthorRecord;
import de.vorb.npmstat.persistence.jooq.tables.records.PackageRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>public</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<AuthorRecord, Long> IDENTITY_AUTHOR = Identities0.IDENTITY_AUTHOR;
    public static final Identity<PackageRecord, Long> IDENTITY_PACKAGE = Identities0.IDENTITY_PACKAGE;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AuthorRecord> AUTHOR_PKEY = UniqueKeys0.AUTHOR_PKEY;
    public static final UniqueKey<AuthorRecord> AUTHOR_NAME_KEY = UniqueKeys0.AUTHOR_NAME_KEY;
    public static final UniqueKey<DownloadCountRecord> DOWNLOAD_COUNT_PKEY = UniqueKeys0.DOWNLOAD_COUNT_PKEY;
    public static final UniqueKey<PackageRecord> PACKAGE_PKEY = UniqueKeys0.PACKAGE_PKEY;
    public static final UniqueKey<PackageRecord> PACKAGE_NAME_KEY = UniqueKeys0.PACKAGE_NAME_KEY;
    public static final UniqueKey<PackageAuthorRecord> PACKAGE_AUTHOR_PKEY = UniqueKeys0.PACKAGE_AUTHOR_PKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<DownloadCountRecord, PackageRecord> DOWNLOAD_COUNT__DOWNLOAD_COUNT_PACKAGE_ID_FKEY = ForeignKeys0.DOWNLOAD_COUNT__DOWNLOAD_COUNT_PACKAGE_ID_FKEY;
    public static final ForeignKey<PackageAuthorRecord, PackageRecord> PACKAGE_AUTHOR__PACKAGE_AUTHOR_PACKAGE_ID_FKEY = ForeignKeys0.PACKAGE_AUTHOR__PACKAGE_AUTHOR_PACKAGE_ID_FKEY;
    public static final ForeignKey<PackageAuthorRecord, AuthorRecord> PACKAGE_AUTHOR__PACKAGE_AUTHOR_AUTHOR_ID_FKEY = ForeignKeys0.PACKAGE_AUTHOR__PACKAGE_AUTHOR_AUTHOR_ID_FKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 extends AbstractKeys {
        public static Identity<AuthorRecord, Long> IDENTITY_AUTHOR = createIdentity(Author.AUTHOR, Author.AUTHOR.ID);
        public static Identity<PackageRecord, Long> IDENTITY_PACKAGE = createIdentity(Package.PACKAGE, Package.PACKAGE.ID);
    }

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<AuthorRecord> AUTHOR_PKEY = createUniqueKey(Author.AUTHOR, "author_pkey", Author.AUTHOR.ID);
        public static final UniqueKey<AuthorRecord> AUTHOR_NAME_KEY = createUniqueKey(Author.AUTHOR, "author_name_key", Author.AUTHOR.NAME);
        public static final UniqueKey<DownloadCountRecord> DOWNLOAD_COUNT_PKEY = createUniqueKey(DownloadCount.DOWNLOAD_COUNT, "download_count_pkey", DownloadCount.DOWNLOAD_COUNT.PACKAGE_ID, DownloadCount.DOWNLOAD_COUNT.DATE);
        public static final UniqueKey<PackageRecord> PACKAGE_PKEY = createUniqueKey(Package.PACKAGE, "package_pkey", Package.PACKAGE.ID);
        public static final UniqueKey<PackageRecord> PACKAGE_NAME_KEY = createUniqueKey(Package.PACKAGE, "package_name_key", Package.PACKAGE.NAME);
        public static final UniqueKey<PackageAuthorRecord> PACKAGE_AUTHOR_PKEY = createUniqueKey(PackageAuthor.PACKAGE_AUTHOR, "package_author_pkey", PackageAuthor.PACKAGE_AUTHOR.PACKAGE_ID, PackageAuthor.PACKAGE_AUTHOR.AUTHOR_ID);
    }

    private static class ForeignKeys0 extends AbstractKeys {
        public static final ForeignKey<DownloadCountRecord, PackageRecord> DOWNLOAD_COUNT__DOWNLOAD_COUNT_PACKAGE_ID_FKEY = createForeignKey(de.vorb.npmstat.persistence.jooq.Keys.PACKAGE_PKEY, DownloadCount.DOWNLOAD_COUNT, "download_count__download_count_package_id_fkey", DownloadCount.DOWNLOAD_COUNT.PACKAGE_ID);
        public static final ForeignKey<PackageAuthorRecord, PackageRecord> PACKAGE_AUTHOR__PACKAGE_AUTHOR_PACKAGE_ID_FKEY = createForeignKey(de.vorb.npmstat.persistence.jooq.Keys.PACKAGE_PKEY, PackageAuthor.PACKAGE_AUTHOR, "package_author__package_author_package_id_fkey", PackageAuthor.PACKAGE_AUTHOR.PACKAGE_ID);
        public static final ForeignKey<PackageAuthorRecord, AuthorRecord> PACKAGE_AUTHOR__PACKAGE_AUTHOR_AUTHOR_ID_FKEY = createForeignKey(de.vorb.npmstat.persistence.jooq.Keys.AUTHOR_PKEY, PackageAuthor.PACKAGE_AUTHOR, "package_author__package_author_author_id_fkey", PackageAuthor.PACKAGE_AUTHOR.AUTHOR_ID);
    }
}
