/*
 * Copyright 2012-2017 the original author or authors.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/*
 * This file is generated by jOOQ.
*/
package de.vorb.npmstat.persistence.jooq;


import de.vorb.npmstat.persistence.jooq.tables.Author;
import de.vorb.npmstat.persistence.jooq.tables.DownloadCount;
import de.vorb.npmstat.persistence.jooq.tables.Package;
import de.vorb.npmstat.persistence.jooq.tables.PackageAuthor;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 2058374813;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.author</code>.
     */
    public final Author AUTHOR = de.vorb.npmstat.persistence.jooq.tables.Author.AUTHOR;

    /**
     * The table <code>public.download_count</code>.
     */
    public final DownloadCount DOWNLOAD_COUNT = de.vorb.npmstat.persistence.jooq.tables.DownloadCount.DOWNLOAD_COUNT;

    /**
     * The table <code>public.package</code>.
     */
    public final Package PACKAGE = de.vorb.npmstat.persistence.jooq.tables.Package.PACKAGE;

    /**
     * The table <code>public.package_author</code>.
     */
    public final PackageAuthor PACKAGE_AUTHOR = de.vorb.npmstat.persistence.jooq.tables.PackageAuthor.PACKAGE_AUTHOR;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        List result = new ArrayList();
        result.addAll(getSequences0());
        return result;
    }

    private final List<Sequence<?>> getSequences0() {
        return Arrays.<Sequence<?>>asList(
            Sequences.AUTHOR_ID_SEQ,
            Sequences.PACKAGE_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Author.AUTHOR,
            DownloadCount.DOWNLOAD_COUNT,
            Package.PACKAGE,
            PackageAuthor.PACKAGE_AUTHOR);
    }
}
