/*
 * This file is generated by jOOQ.
*/
package de.vorb.npmstat.persistence.jooq;


import de.vorb.npmstat.persistence.jooq.tables.ChunkRelationSize;
import de.vorb.npmstat.persistence.jooq.tables.ChunkRelationSizePretty;
import de.vorb.npmstat.persistence.jooq.tables.DownloadCount;
import de.vorb.npmstat.persistence.jooq.tables.HypertableRelationSize;
import de.vorb.npmstat.persistence.jooq.tables.HypertableRelationSizePretty;
import de.vorb.npmstat.persistence.jooq.tables.IndexesRelationSize;
import de.vorb.npmstat.persistence.jooq.tables.IndexesRelationSizePretty;
import de.vorb.npmstat.persistence.jooq.tables.ShowTablespaces;
import de.vorb.npmstat.persistence.jooq.tables.records.ChunkRelationSizePrettyRecord;
import de.vorb.npmstat.persistence.jooq.tables.records.ChunkRelationSizeRecord;
import de.vorb.npmstat.persistence.jooq.tables.records.HypertableRelationSizePrettyRecord;
import de.vorb.npmstat.persistence.jooq.tables.records.HypertableRelationSizeRecord;
import de.vorb.npmstat.persistence.jooq.tables.records.IndexesRelationSizePrettyRecord;
import de.vorb.npmstat.persistence.jooq.tables.records.IndexesRelationSizeRecord;
import de.vorb.npmstat.persistence.jooq.tables.records.ShowTablespacesRecord;

import jakarta.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.Field;
import org.jooq.Result;
import org.jooq.impl.DSL;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.chunk_relation_size</code>.
     */
    public static final ChunkRelationSize CHUNK_RELATION_SIZE = de.vorb.npmstat.persistence.jooq.tables.ChunkRelationSize.CHUNK_RELATION_SIZE;

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration.
     */
    @java.lang.Deprecated
    public static Result<ChunkRelationSizeRecord> CHUNK_RELATION_SIZE(Configuration configuration, Object mainTable) {
        return DSL.using(configuration).selectFrom(de.vorb.npmstat.persistence.jooq.tables.ChunkRelationSize.CHUNK_RELATION_SIZE.call(mainTable)).fetch();
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration.
     */
    @java.lang.Deprecated
    public static ChunkRelationSize CHUNK_RELATION_SIZE(Object mainTable) {
        return de.vorb.npmstat.persistence.jooq.tables.ChunkRelationSize.CHUNK_RELATION_SIZE.call(mainTable);
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration.
     */
    @java.lang.Deprecated
    public static ChunkRelationSize CHUNK_RELATION_SIZE(Field<Object> mainTable) {
        return de.vorb.npmstat.persistence.jooq.tables.ChunkRelationSize.CHUNK_RELATION_SIZE.call(mainTable);
    }

    /**
     * The table <code>public.chunk_relation_size_pretty</code>.
     */
    public static final ChunkRelationSizePretty CHUNK_RELATION_SIZE_PRETTY = de.vorb.npmstat.persistence.jooq.tables.ChunkRelationSizePretty.CHUNK_RELATION_SIZE_PRETTY;

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration.
     */
    @java.lang.Deprecated
    public static Result<ChunkRelationSizePrettyRecord> CHUNK_RELATION_SIZE_PRETTY(Configuration configuration, Object mainTable) {
        return DSL.using(configuration).selectFrom(de.vorb.npmstat.persistence.jooq.tables.ChunkRelationSizePretty.CHUNK_RELATION_SIZE_PRETTY.call(mainTable)).fetch();
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration.
     */
    @java.lang.Deprecated
    public static ChunkRelationSizePretty CHUNK_RELATION_SIZE_PRETTY(Object mainTable) {
        return de.vorb.npmstat.persistence.jooq.tables.ChunkRelationSizePretty.CHUNK_RELATION_SIZE_PRETTY.call(mainTable);
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration.
     */
    @java.lang.Deprecated
    public static ChunkRelationSizePretty CHUNK_RELATION_SIZE_PRETTY(Field<Object> mainTable) {
        return de.vorb.npmstat.persistence.jooq.tables.ChunkRelationSizePretty.CHUNK_RELATION_SIZE_PRETTY.call(mainTable);
    }

    /**
     * The table <code>public.download_count</code>.
     */
    public static final DownloadCount DOWNLOAD_COUNT = de.vorb.npmstat.persistence.jooq.tables.DownloadCount.DOWNLOAD_COUNT;

    /**
     * The table <code>public.hypertable_relation_size</code>.
     */
    public static final HypertableRelationSize HYPERTABLE_RELATION_SIZE = de.vorb.npmstat.persistence.jooq.tables.HypertableRelationSize.HYPERTABLE_RELATION_SIZE;

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration.
     */
    @java.lang.Deprecated
    public static Result<HypertableRelationSizeRecord> HYPERTABLE_RELATION_SIZE(Configuration configuration, Object mainTable) {
        return DSL.using(configuration).selectFrom(de.vorb.npmstat.persistence.jooq.tables.HypertableRelationSize.HYPERTABLE_RELATION_SIZE.call(mainTable)).fetch();
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration.
     */
    @java.lang.Deprecated
    public static HypertableRelationSize HYPERTABLE_RELATION_SIZE(Object mainTable) {
        return de.vorb.npmstat.persistence.jooq.tables.HypertableRelationSize.HYPERTABLE_RELATION_SIZE.call(mainTable);
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration.
     */
    @java.lang.Deprecated
    public static HypertableRelationSize HYPERTABLE_RELATION_SIZE(Field<Object> mainTable) {
        return de.vorb.npmstat.persistence.jooq.tables.HypertableRelationSize.HYPERTABLE_RELATION_SIZE.call(mainTable);
    }

    /**
     * The table <code>public.hypertable_relation_size_pretty</code>.
     */
    public static final HypertableRelationSizePretty HYPERTABLE_RELATION_SIZE_PRETTY = de.vorb.npmstat.persistence.jooq.tables.HypertableRelationSizePretty.HYPERTABLE_RELATION_SIZE_PRETTY;

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration.
     */
    @java.lang.Deprecated
    public static Result<HypertableRelationSizePrettyRecord> HYPERTABLE_RELATION_SIZE_PRETTY(Configuration configuration, Object mainTable) {
        return DSL.using(configuration).selectFrom(de.vorb.npmstat.persistence.jooq.tables.HypertableRelationSizePretty.HYPERTABLE_RELATION_SIZE_PRETTY.call(mainTable)).fetch();
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration.
     */
    @java.lang.Deprecated
    public static HypertableRelationSizePretty HYPERTABLE_RELATION_SIZE_PRETTY(Object mainTable) {
        return de.vorb.npmstat.persistence.jooq.tables.HypertableRelationSizePretty.HYPERTABLE_RELATION_SIZE_PRETTY.call(mainTable);
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration.
     */
    @java.lang.Deprecated
    public static HypertableRelationSizePretty HYPERTABLE_RELATION_SIZE_PRETTY(Field<Object> mainTable) {
        return de.vorb.npmstat.persistence.jooq.tables.HypertableRelationSizePretty.HYPERTABLE_RELATION_SIZE_PRETTY.call(mainTable);
    }

    /**
     * The table <code>public.indexes_relation_size</code>.
     */
    public static final IndexesRelationSize INDEXES_RELATION_SIZE = de.vorb.npmstat.persistence.jooq.tables.IndexesRelationSize.INDEXES_RELATION_SIZE;

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration.
     */
    @java.lang.Deprecated
    public static Result<IndexesRelationSizeRecord> INDEXES_RELATION_SIZE(Configuration configuration, Object mainTable) {
        return DSL.using(configuration).selectFrom(de.vorb.npmstat.persistence.jooq.tables.IndexesRelationSize.INDEXES_RELATION_SIZE.call(mainTable)).fetch();
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration.
     */
    @java.lang.Deprecated
    public static IndexesRelationSize INDEXES_RELATION_SIZE(Object mainTable) {
        return de.vorb.npmstat.persistence.jooq.tables.IndexesRelationSize.INDEXES_RELATION_SIZE.call(mainTable);
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration.
     */
    @java.lang.Deprecated
    public static IndexesRelationSize INDEXES_RELATION_SIZE(Field<Object> mainTable) {
        return de.vorb.npmstat.persistence.jooq.tables.IndexesRelationSize.INDEXES_RELATION_SIZE.call(mainTable);
    }

    /**
     * The table <code>public.indexes_relation_size_pretty</code>.
     */
    public static final IndexesRelationSizePretty INDEXES_RELATION_SIZE_PRETTY = de.vorb.npmstat.persistence.jooq.tables.IndexesRelationSizePretty.INDEXES_RELATION_SIZE_PRETTY;

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration.
     */
    @java.lang.Deprecated
    public static Result<IndexesRelationSizePrettyRecord> INDEXES_RELATION_SIZE_PRETTY(Configuration configuration, Object mainTable) {
        return DSL.using(configuration).selectFrom(de.vorb.npmstat.persistence.jooq.tables.IndexesRelationSizePretty.INDEXES_RELATION_SIZE_PRETTY.call(mainTable)).fetch();
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration.
     */
    @java.lang.Deprecated
    public static IndexesRelationSizePretty INDEXES_RELATION_SIZE_PRETTY(Object mainTable) {
        return de.vorb.npmstat.persistence.jooq.tables.IndexesRelationSizePretty.INDEXES_RELATION_SIZE_PRETTY.call(mainTable);
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration.
     */
    @java.lang.Deprecated
    public static IndexesRelationSizePretty INDEXES_RELATION_SIZE_PRETTY(Field<Object> mainTable) {
        return de.vorb.npmstat.persistence.jooq.tables.IndexesRelationSizePretty.INDEXES_RELATION_SIZE_PRETTY.call(mainTable);
    }

    /**
     * The table <code>public.show_tablespaces</code>.
     */
    public static final ShowTablespaces SHOW_TABLESPACES = de.vorb.npmstat.persistence.jooq.tables.ShowTablespaces.SHOW_TABLESPACES;

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration.
     */
    @java.lang.Deprecated
    public static Result<ShowTablespacesRecord> SHOW_TABLESPACES(Configuration configuration, Object hypertable) {
        return DSL.using(configuration).selectFrom(de.vorb.npmstat.persistence.jooq.tables.ShowTablespaces.SHOW_TABLESPACES.call(hypertable)).fetch();
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration.
     */
    @java.lang.Deprecated
    public static ShowTablespaces SHOW_TABLESPACES(Object hypertable) {
        return de.vorb.npmstat.persistence.jooq.tables.ShowTablespaces.SHOW_TABLESPACES.call(hypertable);
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration.
     */
    @java.lang.Deprecated
    public static ShowTablespaces SHOW_TABLESPACES(Field<Object> hypertable) {
        return de.vorb.npmstat.persistence.jooq.tables.ShowTablespaces.SHOW_TABLESPACES.call(hypertable);
    }
}
