/*
 * Copyright 2012-2017 the original author or authors.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/*
 * This file is generated by jOOQ.
*/
package de.vorb.npmstat.persistence.jooq;


import de.vorb.npmstat.persistence.jooq.tables.Author;
import de.vorb.npmstat.persistence.jooq.tables.DownloadCount;
import de.vorb.npmstat.persistence.jooq.tables.Package;
import de.vorb.npmstat.persistence.jooq.tables.PackageAuthor;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.author</code>.
     */
    public static final Author AUTHOR = de.vorb.npmstat.persistence.jooq.tables.Author.AUTHOR;

    /**
     * The table <code>public.download_count</code>.
     */
    public static final DownloadCount DOWNLOAD_COUNT = de.vorb.npmstat.persistence.jooq.tables.DownloadCount.DOWNLOAD_COUNT;

    /**
     * The table <code>public.package</code>.
     */
    public static final Package PACKAGE = de.vorb.npmstat.persistence.jooq.tables.Package.PACKAGE;

    /**
     * The table <code>public.package_author</code>.
     */
    public static final PackageAuthor PACKAGE_AUTHOR = de.vorb.npmstat.persistence.jooq.tables.PackageAuthor.PACKAGE_AUTHOR;
}
