/*
 * This file is generated by jOOQ.
*/
package de.vorb.npmstat.persistence.jooq;


import de.vorb.npmstat.persistence.jooq.tables.DownloadCount;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.download_count</code>.
     */
    public static final DownloadCount DOWNLOAD_COUNT = de.vorb.npmstat.persistence.jooq.tables.DownloadCount.DOWNLOAD_COUNT;
}
